resource_group_name     = "pollinateRGG"
resource_group_location = "uksouth"
app_service_plan_name   = "pollappserviceplan23"
app_service_name        = "pollinate-webb"
sql_server_name         = "pollinate-sqlserver-022"
sql_database_name       = "ProductsDBG"
sql_admin_login         = "AlexG2"
sql_admin_password      = "Polinate2023@"
