resource_group_name     = "pollinateRG"
resource_group_location = "uksouth"
app_service_plan_name   = "pollappserviceplan"
app_service_name        = "pollinate-web"
sql_server_name         = "pollinate-sqlserver-021"
sql_database_name       = "ProductsDB"
sql_admin_login         = "AlexG"
sql_admin_password      = "Polinate2022@"